# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(help_text='To shorten the text preview at a particular point add [short] to the text.')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('keep_on_homepage', models.BooleanField(default=False, help_text='If checked, the news will stay on the homepage even if it is not one of the most recent ones.')),
                ('hide', models.BooleanField(default=False, help_text='If checked, the news will not be displayed to users.')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
