# Generated by Django 2.0.2 on 2018-08-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpossibility',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='answer_possibilities',
            field=models.TextField(blank=True, help_text='If this is a list question, write down the answer possibilities to be displayed in that list seperated by a semicolon (;).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='help_text',
            field=models.TextField(blank=True, help_text='An optional help text, to clear up what is expected from the user.', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='qtype',
            field=models.CharField(choices=[('B', 'boolean'), ('L', 'list'), ('D', 'date'), ('T', 'text'), ('C', 'country')], help_text="Boolean: will be rendered as 'Yes/No'. List displays a drop-down menu. Text is a free-text answer.", max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(help_text='The question to be asked.'),
        ),
        migrations.DeleteModel(
            name='AnswerPossibility',
        ),
    ]
