# Generated by Django 2.0.2 on 2018-08-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20180807_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='internal_name',
            field=models.CharField(default='bla', help_text='A short internal name to easily select questions.', max_length=64),
            preserve_default=False,
        ),
    ]
